version: '3.3'
services:
  onfhir-feast:
    image: srdc/onfhir-feast
    container_name: onfhir-feast
    command: ["extract-dataset --pipeline https://datatools4heart.eu/feature-sets/study1_dataset_minimal"]
    environment:
      DB_HOST: postgresql
      KAFKA_SERVER_0: kafka-1:29092
      DEFINITIONS_FOLDER: /usr/local/onfhir-feast/definitions
      FHIR_REPO_URL: http://onfhir:8080/fhir
    networks:
      - onfhir-network
    volumes:
      - ../definitions:/usr/local/onfhir-feast/definitions
  postgresql:
    image: timescale/timescaledb-ha:pg16
    container_name: onfhir-feast-db
    ports:
      - 6433:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'onfhir_feast'
      POSTGRES_MAX_CONNECTIONS: 100
    networks:
      - onfhir-network
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
    networks:
      - onfhir-network
  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    ports:
      - 9192:9192
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:29093,PLAINTEXT_HOST://0.0.0.0:9192'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9192'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
    networks:
      - onfhir-network
networks:
  onfhir-network:
    name: onfhir-network
    external: true
