services:
#  onfhir-feast-cli:
#    image: srdc/onfhir-feast-cli:latest
#    container_name: dt4h-onfhir-feast-cli
#    environment:
#      - APP_CONF_FILE=/usr/local/onfhir-feast/conf/docker/feast-cli.conf
#      - JAVA_OPTIONS=-Xms2g -Xmx24g
#    networks:
#      - onfhir-network
#    volumes:
#      - ./feature-extraction-suite:/usr/local/onfhir-feast/conf
#      - ./feature-extraction-suite/output-data:/usr/local/onfhir-feast/output-data
  postgres:
    image: postgres:latest
    container_name: dt4h-feast-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onfhir_feast_new
    networks:
      - onfhir-network
  onfhir-feast:
    image: srdc/onfhir-feast:latest
    container_name: dt4h-feast
    restart: always
    environment:
      APP_CONF_FILE: /usr/local/onfhir-feast/conf/docker/feast-server.conf
    ports:
      - "6095:8085"
    volumes:
      - ./feature-extraction-suite:/usr/local/onfhir-feast/conf
      - ./feature-extraction-suite/output-data:/usr/local/onfhir-feast/output-data
    networks:
      - onfhir-network
networks:
  onfhir-network:
    name: onfhir-network
    external: true
