services:
  onfhir-feast-cli:
    image: srdc/onfhir-feast-cli:latest
    container_name: dt4h-onfhir-feast-cli
    environment:
      - APP_CONF_FILE=/usr/local/onfhir-feast/conf/docker/feast-cli.conf
      - JAVA_OPTIONS=-Xms2g -Xmx24g
    networks:
      - onfhir-network
    volumes:
      - ./feature-extraction-suite:/usr/local/onfhir-feast/conf
      - ./feature-extraction-suite/output-data:/usr/local/onfhir-feast/output-data
networks:
  onfhir-network:
    name: onfhir-network
    external: true
